ROOTDIR: {"darwin": "/y", "windows": "Y:"}
BRUKERSPECTROMETERS: ['n4', 'e7', 'b4', 'a4']
VARIANSPECTROMETERS: ['p6', 'c5']
E7N4 : ['e7', 'n4']
A4B4 : ['a4', 'b4']
B4A4 : ['b4', 'a4']
P6C5 : ['p6', 'c5']
N4  : ['n4',]
KNOWNGROUPS: ['DP',
 'PRM',
 'MOK',
 'PGS',
 'JWW',
 'MRB',
 'DRWH',
 'EXT',
 'AMOD',
 'AJA',
 'IRB',
 'JAGW',
 'AW',
 'GS',
 'SLC',
 'RAT',
 'CFH',
 'NMS',
 'JWS',
 'RP',
 'Y3L',
 'LRH',
 'JSW',
 'EJG',
 'JWG',
 'PWD',
 'MRG',
 'BZ',
 'IRB',
 'JMS',
 'RAGT',
 'AB',
 'RG',
 'PGS',
 'BZ',
 'DM',
 'CSM',
 'KSC',
 'RK',
 'SJC',
 'HCG',
 'PHA']

column_headers: ['date',
                'spectrometer',
                'file',
                'group_id',
                'grant_id',
                'member_id',
                'sample_id',
                'title',
                'expt_num',
                'sequence',
                'solvent',
                'obs_nuc',
                'startdate',
                'enddate',
                'duration',
                'data_location',
                ]

grant_summary_headers: ['Service',
                        'Instrument',
                        'Pi Name',
                        'Submitter',
                        'Grant code',
                        'Sample Name',
                        'Time per sample (h)',
                        'Acquisition Date and Time',
                        'Charging model',
                        'data Identifier',
                        'costperhour',
                        'Experiment Cost (£)']

grant_to_column_map: {'Service': 'Service',
                      'Instrument': 'spectrometer',
                      'Pi Name': 'group_id',
                      'Submitter': 'member_id',
                      'Grant code': 'grant_id',
                      'Sample Name': 'sample_id',
                      'Time per sample (h)': 'duration',
                      'Acquisition Date and Time': 'startdate',
                      'Charging model': 'Charging model',
                      'data Identifier': 'data_location',
                      'costperhour': 'costperhour',
                      'Experiment Cost (£)': 'hourly_cost'}

pi_code_to_name_map: {'AB': 'A. Beeby', 
                      'AF': 'A. Franchino',
                      'AMOD': "A. C. O'Donoghue",
                      'AW': 'A. Whiting',
                      'CSM': 'C. Mahon',
                      'DJT': D. J. Tozer',
                      'DRWH': 'D. R. W. Hodgson',
                      'EXT': 'EXT',
                      'IRB': 'I. R. Baxendale',
                      'JAGW': 'J. A. G. Williams',
                      'JMS': 'J. M. Sanderson',
                      'JWS': 'J. W. Steed',
                      'JWW': 'J. W. Walton',
                      'KJ': 'Karen Johnston',
                      'MAF': 'M. A. Fox',
                      'MOK': 'M. O. Kitching',
                      'MRB': 'M. R. Bryce',
                      'MRW': 'M. R. Wilson',
                      'NMS': 'NMS',
                      'PB': 'P. Brook',
                      'PGS': 'P. G. Steel',
                      'PRM': 'P. R. McGonigal',
                      'PWD': 'P. W. Dyer',
                      'RAT': 'R. A. Taylor',
                      'RP': 'R. Pal',
                      'RT': 'R. Thompson',
                      'SCB': 'S. C. Beaumont',
                      'SLC': 'S. L. Cobb',
                      'WDB': 'W. D. Brittain'
}